#!/bin/bash
echo ""
echo "--------Partial Matches----------"
ag "class .*$1.*\(.*$" ~/repos/zfleischman/models.txt
echo ""
echo "--------Exact Matches----------"
ag "class $1\(.*$" ~/repos/zfleischman/models.txt
echo ""
