#!/bin/bash
#~/nfs-share/website/counsyl/product/manage.py test --retest --run-all --nologcapture 

~/nfs-share/website/counsyl/product/manage.py test --retest --run-all --nologcapture counsyl.product.ordering.conversion.tests.test_conversions:LinkedProfileConversionTest

