#!/bin/bash

methods_cache=~/repos/zfleischman/search_cache/methods.txt

# Generate the cache if necessary
if [ ! -f $methods_cache ]; then
    generate_cache_methods
fi

echo ""
echo "--------Partial Matches----------"
ag "def .*$1.*\(.*$" $methods_cache
echo ""
echo "--------Exact Matches----------"
ag "def $1\(.*$" $methods_cache
echo ""
