#!/bin/bash

models_cache=~/repos/zfleischman/search_cache/models.txt

# Generate the cache if necessary
if [ ! -f $models_cache ]; then
    generate_cache_models
fi

echo ""
echo "--------Partial Matches----------"
ag "class .*$1.*\(.*$" $models_cache
echo ""
echo "--------Exact Matches----------"
ag "class $1\(.*$" $models_cache
echo ""
