#!/bin/bash
# ~/nfs-share/website/counsyl/product/manage.py test --retest --run-all --nologcapture 

~/nfs-share/website/counsyl/product/manage.py test --retest --run-all --nologcapture counsyl.product.order.tests.test_cart_conversion:TestFPSAndIPSOrders.test_merge_linked_profile
