#!/bin/bash

pushd . > /dev/null
cd ~/repos/website
echo "--------------------------------------------------------------------------------"
echo ""
echo "Compiling code..."
echo "================="
make gitlint 2>/dev/null
let error=$?

if [ $error -eq 0 ]
then
    echo "Code is Perfect!"
else
    echo ""
    echo "Errors on lines:"
    echo "================="
    make gitlint 2>/dev/null | sed -n 's/.*\/\(.*\.py\):\([0-9]*\).*/\2:\1/p' 
    echo ""
    echo "================"
    echo "Code is Fucked!"
    echo "================"
fi
popd > /dev/null
