#!/bin/sh

# Show logs for an author

author=
if [ $# -eq 1 ]
    then
        author=$1
        git log --pretty=format:"%Cred%h%Creset - %C(bold blue)<%an>%Creset %Cgreen(%cr)%Creset %C(cyan)- %C(reset)%s %C(yellow)%d%Creset" --abbrev-commit --date=relative -20 --color=always  --author=$author | nl
fi


if [ $# -eq 2 ]
    then
        author=$1
        choice=$2
        pchar=p
        git log --abbrev-commit --oneline --date=relative --color=never  --author=$author | sed -n $choice$pchar | awk '{ print $1 }' | xargs dtshow
fi

