#!/bin/sh

# Lists the changed files in working copy
# Can pass a number as an optional argument and it will diff that particular
#   file 

if [ $# -eq 0 ]
    then
        git --no-pager diff --name-status | nl
elif [ $# -eq 1 ]
    then
        root=$(git rev-parse --show-toplevel)
        file=$(git --no-pager diff --name-status | sed -n $1p | awkc 2)
        git difftool -- $root/$file
fi
