#!/bin/sh

# Lists the changed files compared to master
# Can pass a number as an optional argument and it will diff that particular
#   file (as mapped to by dms without args) against master.

if [ $# -eq 0 ]
    then
        git --no-pager diff --name-status master | nl
elif [ $# -eq 1 ]
    then
        root=$(git rev-parse --show-toplevel)
        file=$(git --no-pager diff --name-status master | sed -n $1p | awkc 2)
        git diff master -- $root/$file
fi
