#!/bin/sh

# Difftool a specific change or range of changes
# Give it a commit

if [ $# -eq 0 ]
    then
        git difftool HEAD
elif [ $# -eq 1 ] 
    then
        carrot=^
        git difftool $1$carrot $1
elif [ $# -eq 2 ] 
    then
        git difftool $1 $2
fi
