#!/bin/sh
num=
branch=

if [ $# -eq 1 ]
    then
        num=$1
fi

if [ $# -eq 2 ]
    then
        num=$1
        branch=$2
        git branch | awk -v "mybranch=$branch" '{ if( $1 == "*") print "\n     Branch: \033[1;35m",  mybranch, "\033[0m \n" }' 
    else
        git branch | awk '{ if( $1 == "*") print "\n     Branch: \033[1;35m", $2, "\033[0m \n" }' 
fi

if [ $# -eq 0 ]
    then
        git log --pretty=format:"%Cred%h%Creset - %C(bold blue)<%an>%Creset %Cgreen(%cd)%Creset %C(cyan)- %C(reset)%s %C(yellow)%d%Creset" --date=local --abbrev-commit --color=always | nl | less
    else
        git log --pretty=format:"%Cred%h%Creset - %C(bold blue)<%an>%Creset %Cgreen(%cd)%Creset %C(cyan)- %C(reset)%s %C(yellow)%d%Creset" --date=local --abbrev-commit $num --color=always $branch | nl
fi

echo "\n"
