#!/bin/sh

# gitlogmine: Pretty prints a git log of my commits.

num=
if [ $# -eq 1 ]
    then
        num=$1
fi


git log --author="leischman" --pretty=format:"%Cred%h%Creset - %C(bold blue)<%an>%Creset %Cgreen(%cr)%Creset %C(cyan)- %C(reset)%s %C(yellow)%d%Creset" --abbrev-commit --date=relative $num --color=always | nl 

echo "\n"
