#!/bin/sh
branch=
num=-30
if [ $# -eq 1 ]
    then
        branch=$1
fi

if [ $# -eq 2 ]
    then
        branch=$1
        num=$2
fi
prefixcmd='gitlog $num $branch | sed -n 1,3p'
prefix=$(eval $prefixcmd)
echo "$prefix\n"

gitlog $num $branch | sed -n 4,\$p | grep -v Merge | awk '{$1=""; print}' | nl




