#!/bin/sh
# Prints only my commit logs
if [ $# -eq 0 ]
    then
        git mine | nl | less
fi

if [ $# -eq 1 ]
    then
        commit=$1
        printChar=p
        git minenocolor | nl | sed -n $commit$printChar | awk '{ print $2 }' | xargs dt
fi

