#!/bin/sh
# Prints only my commit logs
if [ $# -eq 0 ]
    then
        gitlogmine | less
fi

if [ $# -eq 1 ]
    then
        commit=$1
        printChar=p
        gitlogmine_nocolor | sed -n $commit$printChar | awk '{ print $1 }' | xargs dt
fi

