#!/bin/sh

# Lists the current changed files against HEAD
# Can pass a number as an optional argument and it will open that particular
#   file in vim

if [ $# -eq 0 ]
    then
        git --no-pager diff --name-status | nl
elif [ $# -eq 1 ]
    then
        root=$(git rev-parse --show-toplevel)
        file=$(git --no-pager diff --name-status | sed -n $1p | awkc 2)
        vim $root/$file
fi
