#!/bin/sh
num=-10
if [ $# -eq 1 ]
    then
        filename=$1
        git log --pretty=format:"%Cred%h%Creset - %C(bold blue)<%an>%Creset %Cgreen(%cr)%Creset %C(cyan)- %C(reset)%s %C(yellow)%d%Creset" --abbrev-commit --date=relative -40 --color=always -- $filename | nl
fi

if [ $# -eq 2 ]
    then
        filename=$1
        commit=$2
        printChar=p
        git log --oneline -40 -- $filename | sed -n $commit$printChar | awk '{ print $1 }' | xargs timetravel $filename
fi

