#!/usr/bin/zsh
source ~/repos/scripts/util/exportColors

# Change this if you fork the repo
AUTHOR="Zack Fleischman <zFleischman@gmail.com>"

commitMessage="[Backup Script]"
if [ $# -eq 1 ]
then
    commitMessage="[Backup Script] $1"
fi

pushd . > /dev/null
echo "${Cyan}--------------------------${Reset}"
echo "${Cyan}Backing up config files...${Reset}"
echo "${Cyan}--------------------------${Reset}"
cd ~/repos/config
find . -name "*.pyc" -type f -delete
git add :/

DIRTY="$(git diff --shortstat 2> /dev/null | tail -n1)$(git diff --cached --shortstat 2> /dev/null | tail -n1)"
if [ "$DIRTY" "==" "" ]
then
    echo "${Cyan}Everything already backed up.${Reset}"
else
    git --no-pager diff --cached --name-only | awk '{ printf "Backing up: %s\n", $1 }'
    echo ""
    git commit --author="$AUTHOR" -m "$commitMessage"
    git push origin master
fi


echo ""
echo "${Cyan}---------------------${Reset}"
echo "${Cyan}Backing up scripts...${Reset}"
echo "${Cyan}---------------------${Reset}"
cd ~/repos/scripts
find . -name "*.pyc" -type f -delete
git add :/

DIRTY="$(git diff --shortstat 2> /dev/null | tail -n1)$(git diff --cached --shortstat 2> /dev/null | tail -n1)"
if [ "$DIRTY" "==" "" ]
then
    echo "${Cyan}Everything already backed up.${Reset}"
else
    git --no-pager diff --cached --name-only | awk '{ printf "Backing up: %s\n", $1 }'
    echo ""
    git commit --author="$AUTHOR" -m "$commitMessage"
    git push origin master
fi


echo ""
echo "${Green}----------------${Reset}"
echo "${Green}Backup Complete!${Reset}"
echo "${Green}----------------${Reset}"
echo ""
popd > /dev/null
