#!/bin/sh

pushd . > /dev/null

# Getting Config file changes
cd ~/repos/config
git add :/
echo ""
echo "Config Files Modified"
echo "---------------------"
git --no-pager diff --cached --name-only 
git reset HEAD -- . > /dev/null

# Getting Script file changes
cd ~/repos/scripts
git add :/
echo ""
echo "Script Files Modified"
echo "---------------------"
git --no-pager diff --cached --name-only 
git reset HEAD -- . > /dev/null

echo ""
popd > /dev/null
