#!/bin/sh

pushd . > /dev/null
echo "------------------------"
echo "Updating config files..."
echo "------------------------"
cd ~/repos/config
git pull

echo ""
echo "-------------------"
echo "Updating scripts..."
echo "-------------------"
cd ~/repos/scripts
git pull
echo ""

popd > /dev/null
