#!/bin/sh

pushd . > /dev/null
echo "--------------------------"
echo "Backing up config files..."
echo "--------------------------"
cd ~/repos/config
git add :/
git --no-pager diff --cached --name-only | awk '{ printf "Backing up: %s\n", $1 }'
echo ""
git commit -m "Running backup script..."
git push origin master


echo ""
echo "---------------------"
echo "Backing up scripts..."
echo "---------------------"
cd ~/repos/scripts
git add :/
git --no-pager diff --cached --name-only | awk '{ printf "Backing up: %s\n", $1 }'
echo ""
git commit -m "Running backup script..."
git push origin master

echo ""
echo "Backup Complete!"
echo ""
popd > /dev/null
