#!/bin/sh

pushd . > /dev/null

# Getting Config file changes
cd ~/repos/config
git add :/
git difftool --cached
git reset HEAD -- . > /dev/null

# Getting Script file changes
cd ~/repos/scripts
git add :/
git difftool --cached
git reset HEAD -- . > /dev/null

echo ""
popd > /dev/null
