#!/bin/sh

# Export the color variables if they aren't already
source ~/repos/scripts/util/exportColors

# Red
echo ""
echo "${Red}Red\t\t\\\\033[0;31m${Reset}"
echo "${BRed}BRed\t\t\\\\033[1;31m${Reset}"
echo "${URed}URed\t\t\\\\033[4;31m${Reset}"
echo "${On_Red}On_Red\t\t\\\\033[41m${Reset}"
echo "${On_IRed}On_IRed\t\t\\\\033[0;101m${Reset}"

# Green
echo ""
echo "${Green}Green\t\t\\\\033[0;32m${Reset}"
echo "${BGreen}BGreen\t\t\\\\033[1;32m${Reset}"
echo "${UGreen}UGreen\t\t\\\\033[4;32m${Reset}"
echo "${On_Green}On_Green\t\\\\033[42m${Reset}"
echo "${On_IGreen}On_IGreen\t\\\\033[0;102m${Reset}"

# Blue
echo ""
echo "${Blue}Blue\t\t\\\\033[0;34m${Reset}"
echo "${BBlue}BBlue\t\t\\\\033[1;34m${Reset}"
echo "${UBlue}UBlue\t\t\\\\033[4;34m${Reset}"
echo "${On_Blue}On_Blue\t\t\\\\033[44m${Reset}"
echo "${On_IBlue}On_IBlue\t\\\\033[0;104m${Reset}"

# Yellow
echo ""
echo "${Yellow}Yellow\t\t\\\\033[0;33m${Reset}"
echo "${BYellow}BYellow\t\t\\\\033[1;33m${Reset}"
echo "${UYellow}UYellow\t\t\\\\033[4;33m${Reset}"
echo "${On_Yellow}On_Yellow\t\\\\033[43m${Reset}"
echo "${On_IYellow}On_IYellow\t\\\\033[0;103m${Reset}"

# Purple
echo ""
echo "${Purple}Purple\t\t\\\\033[0;35m${Reset}"
echo "${BPurple}BPurple\t\t\\\\033[1;35m${Reset}"
echo "${UPurple}UPurple\t\t\\\\033[4;35m${Reset}"
echo "${On_Purple}On_Purple\t\\\\033[45m${Reset}"
echo "${On_IPurple}On_IPurple\t\\\\033[0;105m${Reset}"

# Cyan
echo ""
echo "${Cyan}Cyan\t\t\\\\033[0;36m${Reset}"
echo "${BCyan}BCyan\t\t\\\\033[1;36m${Reset}"
echo "${UCyan}UCyan\t\t\\\\033[4;36m${Reset}"
echo "${On_Cyan}On_Cyan\t\t\\\\033[46m${Reset}"
echo "${On_ICyan}On_ICyan\t\\\\033[0;106m${Reset}"

# White
echo ""
echo "${White}White\t\t\\\\033[0;37m${Reset}"
echo "${BWhite}BWhite\t\t\\\\033[1;37m${Reset}"
echo "${UWhite}UWhite\t\t\\\\033[4;37m${Reset}"
echo "${On_White}On_White\t\\\\033[47m${Reset}"
echo "${On_IWhite}On_IWhite\t\\\\033[0;107m${Reset}"

# Black
echo ""
echo "${BBlack}BBlack\t\t\\\\033[1;30m${Reset}"
echo "${On_Black}On_Black\t\\\\033[40m${Reset}"
echo "${On_IBlack}On_IBlack\t\\\\033[0;100m${Reset}"
echo "${Black}Black\t\t\\\\033[0;30m${Reset}"
echo "${UBlack}UBlack\t\t\\\\033[4;30m${Reset}"
