#!/bin/sh

# Global find file
function ff() {
if [ $# -eq 1 ]
then
    find . -iname "*$1*" | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    line=$2
    vim $(find . -iname "*$1*" | sed -n "$line p")
fi
} 

# Find file in Farm 2 repo
function fz() {
if [ $# -eq 1 ]
then
    find ~/repos/website/counsyl/product/ -iname "*$1*" | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    line=$2
    vim $(find ~/repos/website/counsyl/product/ -iname "*$1*" | sed -n "$line p")
fi
} 
