#!/bin/sh

# Global find file
function ff() {
if [ $# -eq 1 ]
then
    find . -iname "*$1*" | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    line=$2
    vim $(find . -iname "*$1*" | sed -n "$line p")
fi
} 

# Find file in Counsyl repo
function fff() {
if [ $# -eq 1 ]
then
    find ~/repos/website/counsyl/product/ -iname "*$1*" | grep -v .pyc | sed -e 's/\/home\/zfleischman\/repos\/website\/counsyl\/product//' | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    line=$2
    vim $(find ~/repos/website/counsyl/product/ -iname "*$1*" | grep -v .pyc | sed -n "$line p")
fi
} 
