#!/bin/sh
if [ ! -f $1 ]
    then
        touch $1
        chmod 755 $1
        echo "#!/bin/bash" > $1
        vim $1
    else
        echo "$1 already exists at:"
        which $1
        exit -1
fi
