#!/bin/bash

# This will accept a search term for a process (pid or name) either as the 
# first argument or from stdin and then filter `ps aux` by that search term.

if [ $# -eq 0 ]; then
    read str
else
    str=$1
fi

ps aux | head -1
ps aux | grep --color=always $str | grep --color=always -v grep | grep --color=always -v proc

