#!/bin/bash

# This will accept a search term for a process (pid or name) either as the 
# first argument or from stdin and then wait for that process to finish.

if [ $# -eq 0 ]; then
    read str
else
    str=$1
fi

process_running=1
while [ $process_running -gt 0 ]; do
    process_running=$(ps aux | grep $str | grep -v grep | grep -v waitfor | wc -c)
    sleep 1
done

