#!/bin/bash

#title="Hey Zack, shit's finished yo"
title="Sir, I'm finished."
msg=""

if [ $# -eq 1 ]
    then
        title=$1
fi

if [ $# -eq 2 ]
    then
        title=$1
        msg=$2
fi

/usr/local/bin/growlnotify -m "$msg" -t "$title"
