#!/bin/sh

function ff() {
if [ $# -eq 1 ]
then
    find . -iname "*$1*" | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    find $1 -iname "*$2*" | grep --color=always '[^\/]*$' | nl
fi
} 

function fz() {
if [ $# -eq 1 ]
then
    find ~/repos/farm2 -iname "*$1*" | grep --color=always '[^\/]*$' | nl
elif [ $# -eq 2 ]
then
    line=$2
    cmd="$(find ~/repos/farm2 -iname "*$1*" | sed -n "$line p")"
    cmd2="$(dirname $cmd)"
    cd $cmd2
fi
} 
