#!/bin/sh

echo "Attempting to connect to Dev4..."
COUNT=1
RETVAL=1
while [ $RETVAL -ne 0 ]
do
    ssh -q -q -o "BatchMode=yes" -o "ConnectTimeout 5" farm2-dev-4.zc2.zynga.com "echo 2>&1"
    RETVAL=$?
    [ $RETVAL -eq 0 ] && echo "Success!" && python sendText
    [ $RETVAL -ne 0 ] && echo "Attemp $COUNT failed. Trying again..." && let COUNT=COUNT+1
done

